name: Deploy Hugo Site

on:
  push:
    branches:
      - master  # This should be the branch where your Hugo site content is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.90.1'  # Use your Hugo version

    - name: Build
      run: hugo

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master  # This should be `master` since you're deploying to `master`
        folder: public  # This is the output directory from Hugo
